ub_ss = ss.source_set()
ub_ss.add(files(
  'ub.c',
  'ub_link.c',
  'ub_ubc.c',
  'ub_ummu.c',
  'ub_config.c',
  'ub_acpi.c',
  'ub_enum.c',
  'ub_common.c',
  'ub_usi.c',
  'ub_cna_mgmt.c',
  'ub_sec.c',
  'ub_switch.c',
  'obmm_coherence.c',
  'ub_obmm_async.c',
  'ub_obmm_remote.c',
  'ub_obmm_remote_model.c',
  'ub_async_load.c',
  'ub_async_load_device.c',
  'gsva_key.c',
  'gsva_route.c',
  'gsva_coherence.c',
  'gsva_stats.c',
  'ub_npu.c',
  'ub_ssd.c',
))
system_ss.add_all(when: 'CONFIG_HW_UB', if_true: ub_ss)
subdir('hisi')
